name: Dependabot Auto Merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: contains(fromJson('["dependabot[bot]","app/dependabot"]'), github.event.pull_request.user.login) && github.event.pull_request.draft == false
    steps:
      - name: Auto-approve Dependabot PR
        run: |
          gh pr review \
            --repo "${{ github.repository }}" \
            --approve "${{ github.event.pull_request.number }}" \
            -b "Auto-approved dependency update."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Dependabot PR
        run: |
          gh pr merge \
            --repo "${{ github.repository }}" \
            --squash \
            --delete-branch \
            "${{ github.event.pull_request.number }}" \
          || gh pr merge \
            --repo "${{ github.repository }}" \
            --auto \
            --squash \
            --delete-branch \
            "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
